[main]
  version   = "1.0.0"
  tag       = false
  serialize = "{version}-{banner}"
[[operate]]
  location = "pyproject.toml"
  search   = "version = \"{}\""
  replace  = "version = \"{}\""
[[operate]]
  location = "glimmer/utils/utils.py"
  search   = "__version__ = \"{}\""
  replace  = "__version__ = \"{}\""
