[main]
  serialize = "{version}-{banner}"
  tag = true
  version = "1.2.0"

[[operate]]
  location = "pyproject.toml"
  replace = "version = \"{}\""
  search = "version = \"{}\""

[[operate]]
  location = "glimmer/utils/utils.py"
  replace = "__version__ = \"{}\""
  search = "__version__ = \"{}\""

[[operate]]
  location = "README.md"
  replace = "Current version: {}"
  search = "Current version: {}"